# Generated by Django 3.2.6 on 2021-08-14 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='aktivation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 0, 13, 12, 544236)),
        ),
    ]
