# Generated by Django 3.2.6 on 2021-08-14 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_shopuser_aktivation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='aktivation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 15, 20, 28, 900117)),
        ),
    ]
