# Generated by Django 3.2.6 on 2021-08-14 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_aktivation_key_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='aktivation_key',
            new_name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='aktivation_key_expires',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 18, 2, 34, 967987)),
        ),
    ]
